version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # environment:
      # - NODE_ENV=production
    volumes:
      - /app/node_modules
    networks:
      - my_shared_network


networks:
  my_shared_network:
    external: true
