services:


  flask-server:
    build:
      context: recive-and-serve-server 
      dockerfile: Dockerfile
    ports:
      - "223:223"
    volumes:
      - ./recive-and-serve-server/:/app
      - data:/saveData
      - ./saveData:/saveData
      - sql_db:/DataBaseStore
    networks:
      - my_shared_network

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1


volumes:
  data:
  sql_db:
  mysql_db:
