import type { Metadata } from "next";
import "./globals.css";
// import NavBarMain from "@/components/navbar-props/NavBarMain";


import {Providers} from "./providers";
import Sidebar from "@/components/sidebar-props/sidebar-main";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" >
      <body
        className={`antialiased`}
      >
        <Providers>
          {/* <NavBarMain/> */}
          
        {children}
        </Providers>
      </body>
    </html>
  );
}

