services:
  jupyter-notebook:
    build:
      context: pyspark-image-builder
      dockerfile: Dockerfile
    ports:
      - "4040:4040"  
    volumes:
      - ./pyspark-image-builder/:/home/jovyan/work  
      - data:/saveData
      - sql_db:/home/jovyan/DataBaseStore
    # environment:
    #   JUPYTER_ENABLE_LAB: "yes"  # Enable JupyterLab interface (optional)
    command: [ "python" ,"/home/jovyan/work/main.py" ]
    # command: ["tail", "-f", "/dev/null"]

  flask-server:
    build:
      context: recive-and-serve-server 
      dockerfile: Dockerfile
    ports:
      - "223:223"
    volumes:
      - ./recive-and-serve-server/:/app
      - data:/saveData
      - ./saveData:/saveData
      - sql_db:/DataBaseStore


volumes:
  data:
  sql_db: